version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/python_project
permissions:
  - object: /home/ubuntu/python_project
    owner: root
    mode: 777
    type:
      - directory
hooks:
  BeforeInstall:
    - location: runScript.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: runScript1.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: runScript2.sh
    
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: runScript3.sh
      timeout: 300
      runas: ubuntu
 
       

